version: '2'

services:
    nifi:
        container_name: nifi_local
        image: apache/nifi:latest
        environment:
            NIFI_WEB_HTTP_PORT: '8080'
        ports:
            - 8082:8080
        network_mode: bridge
